services:

  app:
    container_name: app
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    secrets:
      - app_env

  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  mongo-express:
    container_name: db_admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ADMIN}:${DB_PASS}@mongo:27017/app_db?authSource=admin
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

secrets:
  app_env:
    file: ./app/.env
