services:

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    secrets:
      - app_env

  mongodb:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_root
      MONGO_INITDB_ROOT_PASSWORD: tempP@ss1331

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: tempP@ss1331
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

secrets:
  app_env:
    file: ./app/.env
